[package]
name = "proton_drive_webdav_bridge_tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1", features = ["api-all"] }
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
